package com.hackathon.tsc.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.hackathon.tsc.pojo.Activity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Service")
@ToString
public class Service {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String serviceID;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "beneficiaryID-index")
    @DynamoDBAttribute
    private String beneficiaryID;

    @DynamoDBAttribute
    private String caseWorkerID;

    @DynamoDBAttribute
    private String organizationName;

    @DynamoDBAttribute
    private String navigatorID;

    @DynamoDBAttribute
    private String serviceName;

    @DynamoDBAttribute
    private List<Activity> activityLog;

    @DynamoDBAttribute
    private List<String> consent;

    @DynamoDBAttribute
    private String status;

    @DynamoDBAttribute
    private List<String> supportingDocs;

    @DynamoDBAttribute
    private String alignedNeed;
}
